import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'

test('settings sections preserve form state, keyboard control, validation, summaries and independent remembered expansion', async () => {
  const root = resolve('.'), profile = join(root, '.test-data', `folding-${Date.now()}`)
  await mkdir(profile, { recursive: true })
  const env = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined && entry[0] !== 'ELECTRON_RUN_AS_NODE'))
  let desktop: ElectronApplication | undefined
  const launch = async () => {
    desktop = await electron.launch({ executablePath: process.env.ROUNDTABLE_EXECUTABLE, args: process.env.ROUNDTABLE_EXECUTABLE ? [] : [root], cwd: process.env.ROUNDTABLE_EXECUTABLE ? dirname(process.env.ROUNDTABLE_EXECUTABLE) : root, env: { ...env, MODEL_ROUNDTABLE_DATA_DIR: profile, MODEL_ROUNDTABLE_TEST: '1' }, timeout: 30000 })
    const page = await desktop.firstWindow()
    page.setDefaultTimeout(15000)
    await expect(page.locator('.welcome-page')).toBeVisible()
    return page
  }
  try {
    let page = await launch()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    const editor = page.locator('[data-section="settings.editor"]')
    await editor.locator(':scope > summary').focus()
    await page.keyboard.press('Enter')
    await expect(editor).toHaveAttribute('open', '')
    await expect(editor.getByRole('heading', { name: '安装扩展', exact: true })).toBeVisible()
    await expect(editor.getByRole('heading', { name: '连接状态', exact: true })).toBeVisible()
    await expect(editor.getByRole('heading', { name: '使用说明', exact: true })).toBeVisible()
    await expect(editor.getByRole('button', { name: '检测编辑器', exact: true })).toHaveCount(0)
    await expect(editor.getByRole('button', { name: '生成配对码', exact: true })).toHaveCount(0)
    await expect(editor.getByRole('link', { name: 'Markdown 原生预览', exact: true })).toHaveAttribute('href', 'https://code.visualstudio.com/docs/languages/markdown')
    await expect(editor).toContainText('首次')
    await expect(editor).toContainText('模型圆桌：发送选中文本')
    await editor.locator(':scope > summary').click()
    await expect(page.locator('[data-section="settings.providers"]')).toHaveAttribute('open', '')
    const search = page.locator('[data-section="settings.search"]')
    await expect(search).not.toHaveAttribute('open')
    await search.locator(':scope > summary').focus()
    await page.keyboard.press('Enter')
    await expect(search).toHaveAttribute('open', '')
    await search.getByLabel('搜索方式').selectOption('searxng')
    await search.getByLabel('SearXNG 地址').fill('https://search.example.org')
    await search.locator(':scope > summary').click()
    await expect(search).not.toHaveAttribute('open')
    await expect(search.locator(':scope > summary')).toContainText('未保存')
    // The field stays mounted with its value while the section is closed.
    await expect(search.getByLabel('SearXNG 地址')).toHaveValue('https://search.example.org')
    await search.locator(':scope > summary').click()
    await search.getByLabel('SearXNG 地址').fill('')
    await search.locator(':scope > summary').click()
    await page.getByRole('button', { name: '保存设置', exact: true }).click()
    await expect(search).toHaveAttribute('open', '')
    await expect(search.getByLabel('SearXNG 地址')).toBeFocused()
    await search.getByLabel('SearXNG 地址').fill('https://search.example.org')
    await page.getByRole('button', { name: '保存设置', exact: true }).click()
    await expect(search.locator(':scope > summary')).not.toContainText('未保存')

    // An action in a collapsed header runs without toggling the section.
    const recovery = page.locator('[data-section="settings.recovery"]')
    await expect(recovery).not.toHaveAttribute('open')
    await recovery.getByRole('button', { name: '检查旧模型配置', exact: true }).click()
    const recoverDialog = page.getByRole('dialog', { name: '恢复旧模型配置', exact: true })
    await expect(recoverDialog).toBeVisible()
    await recoverDialog.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(recovery).not.toHaveAttribute('open')

    await page.getByRole('button', { name: '添加模型服务', exact: true }).click()
    const provider = page.getByRole('dialog', { name: '添加模型服务', exact: true })
    await expect(provider.locator('[data-section="provider.new.connection"]')).toHaveAttribute('open', '')
    await expect(provider.locator('[data-section="provider.new.models"]')).not.toHaveAttribute('open')
    await provider.getByLabel('服务名称', { exact: true }).fill('未保存的输入')
    await provider.getByRole('button', { name: '全部收起', exact: true }).click()
    await expect(provider.locator('.collapsible[open]')).toHaveCount(0)
    await expect(provider.getByLabel('服务名称', { exact: true })).toHaveValue('未保存的输入')
    await provider.getByRole('button', { name: '全部展开', exact: true }).click()
    await expect(provider.locator('.collapsible[open]')).toHaveCount(4)
    await provider.getByLabel('API 地址', { exact: true }).fill('https://example.org/v1')
    await provider.locator('summary').filter({ hasText: '高级连接设置' }).click()
    await provider.getByLabel('请求超时（秒）', { exact: true }).fill('0')
    await provider.getByRole('button', { name: '全部收起', exact: true }).click()
    await provider.getByRole('button', { name: '保存服务', exact: true }).click()
    await expect(provider.locator('[data-section="provider.new.connection"]')).toHaveAttribute('open', '')
    await expect(provider.getByLabel('请求超时（秒）', { exact: true })).toBeFocused()
    expect((await page.evaluate(() => window.roundtable.bootstrap())).providers).toHaveLength(0)
    await provider.getByRole('button', { name: '关闭', exact: true }).click()

    const networkState = await page.evaluate(async () => window.roundtable.importNetworkSubscription({ name: '中文折叠订阅', content: 'proxies:\n  - { name: Alpha, type: http, server: 127.0.0.1, port: 19876 }\n  - { name: Beta, type: http, server: 127.0.0.1, port: 19877 }' }))
    await page.getByRole('button', { name: '网络与订阅', exact: true }).click()
    const subscription = page.locator(`[data-section="network.subscription.${networkState.subscriptions[0].id}"]`)
    await expect(page.locator('[data-section="network.subscriptions"]')).toHaveAttribute('open', '')
    await expect(subscription).not.toHaveAttribute('open')
    await page.getByLabel('筛选订阅节点').fill('Alpha')
    await expect(subscription).toHaveAttribute('open', '')
    await page.getByLabel('选择节点 中文折叠订阅 / Alpha', { exact: true }).check()
    await page.getByRole('button', { name: '清除筛选', exact: true }).click()
    await expect(subscription).not.toHaveAttribute('open')
    await expect(page.locator('[data-section="network.subscriptions"] > summary')).toContainText('已选 1')
    await subscription.locator(':scope > summary').click()
    await expect(page.getByLabel('选择节点 中文折叠订阅 / Alpha', { exact: true })).toBeChecked()
    const routes = page.locator('[data-section="network.bindings"]')
    await expect(routes).not.toHaveAttribute('open')
    await routes.locator(':scope > summary').click()
    await routes.getByLabel('联网搜索', { exact: true }).selectOption('direct')
    await routes.locator(':scope > summary').click()
    await expect(routes.locator(':scope > summary')).toContainText('未保存')
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    const guard = page.getByRole('dialog', { name: '网络设置尚未保存', exact: true })
    await expect(guard).toBeVisible()
    await guard.getByRole('button', { name: '保存并离开', exact: true }).click()
    await expect(search).toHaveAttribute('open', '')
    await expect(recovery).not.toHaveAttribute('open')
    await desktop!.close(); desktop = undefined
    page = await launch()
    await page.getByRole('button', { name: '网络与订阅', exact: true }).click()
    await expect(page.locator(`[data-section="network.subscription.${networkState.subscriptions[0].id}"]`)).toHaveAttribute('open', '')
    await expect(page.locator('[data-section="network.bindings"]')).not.toHaveAttribute('open')
    expect((await page.evaluate(() => window.roundtable.getNetworkState())).bindings.search).toEqual({ mode: 'direct' })
    expect(errors).toEqual([])
  } finally {
    if (desktop) { await desktop.evaluate(({ BrowserWindow }) => { for (const window of BrowserWindow.getAllWindows()) window.destroy() }).catch(() => {}); await desktop.close().catch(() => {}) }
  }
})
