import { test, expect, _electron as electron, type ElectronApplication } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { startMockAPI } from '../helpers/mock-api'
import { componentTestEnv } from '../helpers/components'
import type { AppAPI } from '../../src/shared/types'

declare global { interface Window { roundtable: AppAPI } }

test('daily controls preserve hidden selections and drafts, prevent active deletion, and remove records from sidebar without changing files', async () => {
  test.setTimeout(180000)
  const root = resolve('.')
  const directory = join(root, '.test-data', `usability-${Date.now()}`)
  const projectDirectory = join(directory, '中文项目')
  await mkdir(projectDirectory, { recursive: true })
  await writeFile(join(projectDirectory, 'keep.txt'), '项目文件必须保留')
  const mock = await startMockAPI()
  let desktop: ElectronApplication | undefined
  const errors: string[] = []
  try {
    const env = Object.fromEntries(Object.entries(process.env).filter((entry): entry is [string, string] => entry[1] !== undefined && entry[0] !== 'ELECTRON_RUN_AS_NODE'))
    desktop = await electron.launch({ executablePath: process.env.ROUNDTABLE_EXECUTABLE, args: process.env.ROUNDTABLE_EXECUTABLE ? [] : [root], cwd: process.env.ROUNDTABLE_EXECUTABLE ? dirname(process.env.ROUNDTABLE_EXECUTABLE) : root, env: { ...env, ...componentTestEnv, MODEL_ROUNDTABLE_DATA_DIR: join(directory, 'profile'), MODEL_ROUNDTABLE_TEST: '1' }, timeout: 20000 })
    const page = await desktop.firstWindow()
    page.setDefaultTimeout(15000)
    page.on('pageerror', error => errors.push(error.message))
    await expect(page.locator('.welcome-page')).toBeVisible()
    const fixture = await page.evaluate(async ({ url, projectDirectory }) => {
      const provider = await window.roundtable.saveProvider({ kind: 'api', name: '甲服务', baseUrl: `${url}/v1`, modelIds: ['analyst', 'critic', 'slow', ...Array.from({ length: 32 }, (_, i) => `model-${i}`)], tokenParameter: 'max_tokens', streamUsage: true, timeoutMs: 30000 })
      const second = await window.roundtable.saveProvider({ kind: 'api', name: '乙服务', baseUrl: `${url}/v1`, modelIds: ['beta'], tokenParameter: 'max_tokens', streamUsage: true, timeoutMs: 30000 })
      const project = await window.roundtable.saveProject({ name: '项目甲', directory: projectDirectory, instructions: '', knowledgeBaseIds: [] })
      const otherProject = await window.roundtable.saveProject({ name: '项目乙', directory: projectDirectory, instructions: '', knowledgeBaseIds: [] })
      const base = { projectId: project.id, topic: '快捷管理验收', mode: 'roundtable' as const, participants: ['analyst', 'critic'].map((modelId, i) => ({ id: `seat-${i}`, name: modelId, role: '', model: { providerId: provider.id, modelId } })), searchEnabled: false, knowledgeBaseIds: [], limits: { autoTurns: 12, maxCalls: 20, maxOutputTokens: 500, maxSearches: 5, contextChars: 16000 } }
      const first = await window.roundtable.createSession({ ...base, title: '保留的讨论' })
      const removed = await window.roundtable.createSession({ ...base, title: '要删除的讨论' })
      await window.roundtable.saveDraft({ id: `message.${removed.id}`, text: JSON.stringify({ text: '应被删除的草稿', participantId: '' }) })
      const kb = await window.roundtable.createKnowledgeBase({ name: 'Alpha 资料', embedding: { providerId: provider.id, modelId: 'analyst' } })
      await window.roundtable.createKnowledgeBase({ name: 'Beta 资料', embedding: { providerId: provider.id, modelId: 'analyst' } })
      const execution = await window.roundtable.createExecution({ projectId: project.id, task: '准备中的执行', acceptance: '保留文件', executor: { providerId: provider.id, modelId: 'analyst' }, reviewers: [], maxCalls: 10, maxOutputTokens: 500, timeoutMs: 60000, maxRepairRounds: 0, web: { enabled: false, maxSearches: null } })
      return { provider, second, project, otherProject, first, removed, execution, kb }
    }, { url: mock.url, projectDirectory })
    await expect.poll(async () => page.evaluate(async () => (await window.roundtable.bootstrap()).activeSessionIds?.length ?? 0)).toBe(0)
    await page.reload()
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    await page.locator('.provider-card').filter({ hasText: '甲服务' }).getByRole('button', { name: '管理服务与模型' }).click()
    const providerDialog = page.getByRole('dialog', { name: '管理模型服务' })
    await providerDialog.getByRole('button', { name: '全部展开', exact: true }).click()
    await providerDialog.getByLabel('筛选模型', { exact: true }).fill('analyst')
    await providerDialog.getByRole('button', { name: '取消当前筛选', exact: true }).click()
    await expect(providerDialog.getByRole('checkbox', { name: 'analyst', exact: true })).not.toBeChecked()
    await expect(providerDialog).toContainText('已选 34 · 当前 1')
    await providerDialog.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await expect(providerDialog).toContainText('已选 35 · 当前 1')
    await providerDialog.getByRole('button', { name: '保存服务', exact: true }).click()
    await Promise.race([expect(providerDialog).toHaveCount(0), page.locator('.toast-error').waitFor().then(async () => { throw new Error(await page.locator('.toast-error').innerText()) })])

    await page.getByRole('button', { name: '项目 项目甲', exact: true }).click()
    await page.getByRole('button', { name: '新建项目讨论', exact: true }).click()
    let discussion = page.getByRole('dialog', { name: '开启一次新讨论' })
    await expect(discussion.getByRole('checkbox', { name: '允许自动联网' })).toBeChecked()
    await discussion.locator('summary').filter({ hasText: '讨论与费用限制' }).click()
    await expect(discussion.getByLabel('最多搜索次数', { exact: true })).toHaveValue('')
    await discussion.getByRole('button', { name: '批量添加模型', exact: true }).click()
    let picker = page.getByRole('dialog', { name: '批量添加模型', exact: true })
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await expect(picker.getByRole('button', { name: '添加所选模型', exact: true })).toBeDisabled()
    await expect(picker.getByRole('alert')).toContainText('超过剩余 30 个席位')
    await picker.getByRole('button', { name: '取消当前筛选', exact: true }).click()
    await picker.getByLabel('筛选可添加模型', { exact: true }).fill('analyst')
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await picker.getByLabel('筛选可添加模型', { exact: true }).fill('critic')
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await picker.getByLabel('筛选可添加模型', { exact: true }).fill('beta')
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await picker.getByRole('button', { name: '添加所选模型', exact: true }).click()
    await expect(discussion.locator('.participant-editor')).toHaveCount(3)
    await expect(discussion.getByLabel('成员 1 模型', { exact: true })).toHaveValue(JSON.stringify([fixture.provider.id, 'analyst']))
    await discussion.getByRole('button', { name: '批量添加模型', exact: true }).click()
    picker = page.getByRole('dialog', { name: '批量添加模型', exact: true })
    await expect(picker.getByRole('checkbox', { name: '甲服务 / analyst', exact: true })).toHaveCount(0)
    await picker.getByRole('button', { name: '取消', exact: true }).click()
    await discussion.getByLabel('筛选候选项：成员 1', { exact: true }).fill('not-existing')
    await expect(discussion.getByLabel('成员 1 模型', { exact: true })).toHaveValue(JSON.stringify([fixture.provider.id, 'analyst']))
    const resources = discussion.locator('.session-resources')
    await resources.getByLabel('筛选知识库', { exact: true }).fill('Alpha')
    await resources.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await resources.getByLabel('筛选知识库', { exact: true }).fill('Beta')
    await resources.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await resources.getByRole('button', { name: '取消当前筛选', exact: true }).click()
    await expect(resources).toContainText('已选 1 · 当前 1')
    await discussion.getByRole('checkbox', { name: '允许自动联网' }).uncheck()
    await discussion.getByLabel('最多搜索次数', { exact: true }).fill('7')
    await discussion.getByRole('button', { name: '取消', exact: true }).click()
    await page.getByRole('button', { name: '新建项目讨论', exact: true }).click()
    discussion = page.getByRole('dialog', { name: '开启一次新讨论' })
    await expect(discussion.getByRole('checkbox', { name: '允许自动联网' })).not.toBeChecked()
    await discussion.locator('summary').filter({ hasText: '讨论与费用限制' }).click()
    await expect(discussion.getByLabel('最多搜索次数', { exact: true })).toHaveValue('7')
    await discussion.getByRole('button', { name: '正式辩论 正反交锋 · 质询反驳 · 裁判评议' }).click()
    await discussion.getByRole('button', { name: '批量添加模型', exact: true }).click()
    picker = page.getByRole('dialog', { name: '批量添加模型', exact: true })
    await picker.getByLabel('筛选可添加模型', { exact: true }).fill('slow')
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await expect(picker.getByRole('button', { name: '添加所选模型', exact: true })).toBeDisabled()
    await picker.getByLabel('批量添加阵营').selectOption('con')
    await picker.getByRole('button', { name: '添加所选模型', exact: true }).click()
    await expect(discussion.getByLabel('成员 4 阵营')).toHaveValue('con')
    await discussion.getByRole('button', { name: '取消', exact: true }).click()

    await page.getByRole('button', { name: '新建执行任务', exact: true }).click()
    const task = page.getByRole('dialog', { name: '新建执行任务', exact: true })
    await expect(task.getByRole('checkbox', { name: '允许自动联网' })).toBeChecked()
    await task.getByRole('button', { name: '批量添加模型', exact: true }).click()
    picker = page.getByRole('dialog', { name: '批量添加模型', exact: true })
    await picker.getByRole('button', { name: '全选当前筛选', exact: true }).click()
    await expect(picker.getByRole('alert')).toContainText('超过剩余 8 个席位')
    await picker.getByRole('button', { name: '取消', exact: true }).click()
    await task.getByRole('button', { name: '取消', exact: true }).click()
    await page.evaluate(async projectId => window.roundtable.saveDraft({ id: `execution-new.${projectId}.new`, text: JSON.stringify({ projectId, task: '旧版执行草稿', acceptance: '原有判定', reviewers: [], maxCalls: 60, maxOutputTokens: 8192, timeoutMs: 1800000, maxRepairRounds: 2 }) }), fixture.project.id)
    await page.getByRole('button', { name: '新建执行任务', exact: true }).click()
    await expect(task.getByLabel('要执行的任务', { exact: true })).toHaveValue('旧版执行草稿')
    await expect(task.getByRole('checkbox', { name: '允许自动联网' })).not.toBeChecked()
    await task.getByRole('button', { name: '取消', exact: true }).click()

    await page.locator('.session-item').filter({ hasText: '要删除的讨论' }).click()
    await page.locator('.session-item').filter({ hasText: '保留的讨论' }).click()
    await page.getByRole('button', { name: '讨论 要删除的讨论 更多操作', exact: true }).click()
    await expect(page.locator('.discussion-header h1')).toHaveText('保留的讨论')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('menu')).toHaveCount(0)
    await expect(page.getByRole('button', { name: '讨论 要删除的讨论 更多操作', exact: true })).toBeFocused()
    await page.getByRole('button', { name: '讨论 要删除的讨论 更多操作', exact: true }).click()
    await page.getByRole('menuitem', { name: '删除讨论', exact: true }).click()
    await page.getByRole('button', { name: '确认删除', exact: true }).click()
    await expect(page.locator('.discussion-header h1')).toHaveText('保留的讨论')
    await expect(page.getByRole('tab', { name: '要删除的讨论', exact: true })).toHaveCount(0)
    expect(await page.evaluate(id => window.roundtable.getDraft(`message.${id}`), fixture.removed.id)).toBe('')
    await page.getByRole('button', { name: '执行 准备中的执行 更多操作', exact: true }).click()
    await page.getByRole('menuitem', { name: '删除执行记录', exact: true }).click()
    await page.getByRole('button', { name: '确认删除', exact: true }).click()
    await expect(page.locator('.session-item').filter({ hasText: '准备中的执行' })).toHaveCount(0)
    await page.getByRole('button', { name: '项目 项目乙 更多操作', exact: true }).click()
    await page.getByRole('menuitem', { name: '移除项目', exact: true }).click()
    await page.getByRole('button', { name: '确认删除', exact: true }).click()
    await expect(page.locator('.discussion-header h1')).toHaveText('保留的讨论')
    expect(await readFile(join(projectDirectory, 'keep.txt'), 'utf8')).toBe('项目文件必须保留')
    await page.getByLabel('筛选项目和会话').fill('不存在的名称')
    await expect(page.locator('.session-item')).toHaveCount(0)
    await page.getByRole('button', { name: '清除项目和会话筛选' }).click()
    await expect(page.locator('.session-item')).toHaveCount(1)
    const release = mock.holdSlowStreams()
    const running = await page.evaluate(async providerId => window.roundtable.createSession({ title: '活动中的讨论', topic: '停止保护', mode: 'roundtable', projectId: (await window.roundtable.bootstrap()).projects[0].id, participants: ['slow', 'critic'].map((modelId, i) => ({ id: `slow-${i}`, name: modelId, role: '', model: { providerId, modelId } })), searchEnabled: false, knowledgeBaseIds: [], limits: { autoTurns: 12, maxCalls: 20, maxOutputTokens: 500, maxSearches: null, contextChars: 16000 } }), fixture.provider.id)
    await page.getByRole('button', { name: '讨论 活动中的讨论 更多操作', exact: true }).click()
    await expect(page.getByRole('menuitem', { name: /删除讨论/ })).toBeDisabled()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '项目 项目甲 更多操作', exact: true }).click()
    await expect(page.getByRole('menuitem', { name: /移除项目/ })).toBeDisabled()
    await page.keyboard.press('Escape')
    await page.evaluate(id => window.roundtable.sessionAction({ sessionId: id, action: 'stop' }), running.id)
    release()
    await expect.poll(async () => page.evaluate(async id => (await window.roundtable.bootstrap()).activeSessionIds?.includes(id) ?? false, running.id)).toBe(false)
    await page.getByRole('button', { name: '讨论 活动中的讨论 更多操作', exact: true }).click()
    await expect(page.getByRole('menuitem', { name: '删除讨论', exact: true })).toBeEnabled()
    await page.keyboard.press('Escape')
    await page.screenshot({ path: join(directory, 'sidebar-controls.png') })
    await page.getByRole('button', { name: '网络与订阅', exact: true }).click()
    await page.locator('.network-page').getByRole('button', { name: '全部展开', exact: true }).click()
    await page.getByLabel('联网搜索', { exact: true }).selectOption('direct')
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    let guard = page.getByRole('dialog', { name: '网络设置尚未保存', exact: true })
    await guard.getByRole('button', { name: '继续编辑', exact: true }).click()
    await expect(page.getByRole('heading', { name: '网络与订阅', exact: true })).toBeVisible()
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    guard = page.getByRole('dialog', { name: '网络设置尚未保存', exact: true })
    await guard.getByRole('button', { name: '放弃改动', exact: true }).click()
    await expect(page.getByRole('heading', { name: '连接你的模型', exact: true })).toBeVisible()
    await page.getByRole('button', { name: '网络与订阅', exact: true }).click()
    await page.locator('.network-page').getByRole('button', { name: '全部展开', exact: true }).click()
    await expect(page.getByLabel('联网搜索', { exact: true })).toHaveValue('system')
    await page.getByLabel('联网搜索', { exact: true }).selectOption('direct')
    await page.getByRole('button', { name: '模型与设置', exact: true }).click()
    await page.getByRole('dialog', { name: '网络设置尚未保存', exact: true }).getByRole('button', { name: '保存并离开', exact: true }).click()
    expect((await page.evaluate(() => window.roundtable.getNetworkState())).bindings.search).toEqual({ mode: 'direct' })
    await page.locator('.session-item').filter({ hasText: '保留的讨论' }).click()
    await page.getByRole('button', { name: '讨论 保留的讨论 更多操作', exact: true }).click()
    await page.getByRole('menuitem', { name: '删除讨论', exact: true }).click()
    await page.getByRole('button', { name: '确认删除', exact: true }).click()
    await expect(page.locator('.project-home')).toBeVisible()
    expect(errors).toEqual([])
  } finally { await desktop?.close(); await mock.close() }
})
