import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, CheckCircle2, ChevronRight, FileDiff, FolderOpen, Play, RotateCcw, Square, Terminal, Trash2 } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { Bootstrap, Evidence } from '../../shared/types'
import type { Execution, ExecutionStatus } from '../../shared/execution'
import { api } from './api'
import { SendToEditor } from './EditorIntegration'
import { modelName, useTask, type Notify } from './common'
import { ProjectFiles } from './ProjectFiles'
import { EvidenceDetail } from './KnowledgeView'

export const executionStatusLabel: Record<ExecutionStatus, string> = { ready: '准备执行', running: '执行中', reviewing: '审阅中', stopping: '正在停止', stopped: '已停止', failed: '执行失败', complete: '已完成', needs_attention: '需要处理' }
export function ExecutionView({ execution, data, notify, onDelete, deletionBlocked, onSource }: { execution: Execution; data: Bootstrap; notify: Notify; onDelete: () => void; deletionBlocked: boolean; onSource: (id: string) => void }) {
  const [tab, setTab] = useState<'activity' | 'reviews' | 'evidence'>('activity')
  const [evidence, setEvidence] = useState<Evidence | null>(null)
  const [side, setSide] = useState<'changes' | 'files'>('changes')
  const [path, setPath] = useState('')
  const [terminalOpen, setTerminalOpen] = useState(false)
  const end = useRef<HTMLDivElement>(null)
  const { busy, run } = useTask(notify)
  const active = ['running', 'reviewing', 'stopping'].includes(execution.status)
  const commandEvents = execution.events.filter(event => event.kind === 'tool' && /bash|shell|command|terminal|exec/i.test(event.tool ?? ''))
  const project = data.projects.find(p => p.id === execution.projectId)
  useEffect(() => { if (active) end.current?.scrollIntoView({ block: 'nearest' }) }, [execution.events.length, active])
  const action = (action: 'start' | 'stop' | 'retry') => void run(async () => { await api.executionAction({ id: execution.id, action }) })
  return <div className="execution-layout"><section className="execution-main"><header className="discussion-header"><div><div className="discussion-kicker"><span>执行任务</span><i/><span>{executionStatusLabel[execution.status]}</span></div><h1 title={execution.task}>{execution.task.split('\n')[0].replace(/^#+\s*/, '').slice(0, 85)}</h1></div><div className="header-actions"><button className="icon-button danger-hover" disabled={busy || deletionBlocked} aria-label="删除执行任务" title={deletionBlocked ? '请先停止，等待当前任务结束' : undefined} onClick={onDelete}><Trash2 size={17}/></button></div></header>
    <div className="execution-info"><span><FolderOpen size={14}/>{project?.name ?? execution.rootPath}</span><span>{modelName(execution.executor, data.providers)}</span>{execution.sessionId && <button className="text-button" onClick={() => onSource(execution.sessionId!)}><ArrowLeft size={13}/>来源讨论</button>}</div>
    <div className="run-strip"><span className={active ? 'live-dot' : 'quiet-dot'}/><span>{executionStatusLabel[execution.status]}</span><span className="run-count">{execution.calls} / {execution.maxCalls} 次调用 · 修复 {execution.repairRound} / {execution.maxRepairRounds} 轮</span><div className="run-controls">{active ? <button disabled={busy || execution.status === 'stopping'} onClick={() => action('stop')}><Square size={12}/>停止执行</button> : execution.status === 'ready' ? <button disabled={busy} onClick={() => action('start')}><Play size={13}/>开始执行</button> : ['failed', 'stopped', 'needs_attention'].includes(execution.status) ? <button disabled={busy || execution.calls >= execution.maxCalls} title={execution.calls >= execution.maxCalls ? '本次调用预算已用尽，请新建执行任务' : undefined} onClick={() => action('retry')}><RotateCcw size={13}/>重试执行</button> : null}</div></div>
    <p className="execution-accounting-note">{execution.web?.enabled ? `允许自动联网 · 已搜索 ${execution.searches ?? 0}${execution.web.maxSearches === null ? ' 次 · 不限次数' : ` / ${execution.web.maxSearches} 次`}。` : '未开启自动联网。'}累计执行与审阅：API 按请求计数；官方账号按后台调用计数，不包含其内部 HTTP 请求。</p>
    {execution.error && <div className="session-error" role="alert"><strong>执行需要处理</strong><p>{execution.error}</p></div>}
    <div className="execution-tabs"><button className={tab === 'activity' ? 'active' : ''} onClick={() => setTab('activity')}>任务与过程</button><button className={tab === 'reviews' ? 'active' : ''} onClick={() => setTab('reviews')}>独立审阅 <span>{execution.reviews.length}</span></button><button className={tab === 'evidence' ? 'active' : ''} onClick={() => setTab('evidence')}>执行证据 <span>{execution.toolEvidence?.length ?? 0}</span></button></div>
    <div className="execution-scroll">{tab === 'activity' ? <><details className="task-brief" open={execution.status === 'ready'}><summary>执行任务与完成判定<ChevronRight size={15}/></summary><div className="markdown"><Markdown text={execution.task} notify={notify}/><h3>完成判定</h3><p>{execution.acceptance}</p></div>{execution.snapshotWarnings.map((warning, i) => <p key={i} className="form-hint">{warning}</p>)}</details>
      {execution.events.length ? execution.events.map(event => <article className={`execution-event event-${event.kind}`} key={event.id}><div className="execution-event-heading"><span>{event.kind === 'tool' ? event.tool === 'web_search' ? '联网搜索' : event.tool === 'web_read' ? '读取网页' : event.tool ?? '工具调用' : ({ status: '状态', text: '执行者', request: '请求', error: '错误', review: '审阅' } as Record<string, string>)[event.kind]}</span>{event.state && <small>{event.state === 'running' ? /search/i.test(event.tool ?? '') ? '正在搜索' : /web_read|webpage|fetch/i.test(event.tool ?? '') ? '正在读取网页' : '运行中' : event.state === 'failed' ? '失败' : '完成'}</small>}<time>{new Date(event.at).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</time></div>{event.kind === 'tool' ? <details open={event.state === 'running' || event.state === 'failed'}><summary>查看输入与结果</summary><pre>{event.text}</pre></details> : <div className="markdown"><Markdown text={event.text} notify={notify}/></div>}</article>) : <div className="empty-state compact"><Play size={25}/><p>任务已准备好。开始后会在这里显示真实的执行记录。</p></div>}
      {execution.result && <div className="execution-result"><h3><CheckCircle2 size={18}/>执行结果</h3><SendToEditor projectId={execution.projectId} title="执行结果" text={execution.result} notify={notify}/><div className="markdown"><Markdown text={execution.result} notify={notify}/></div><button onClick={() => { setSide('changes') }}><FileDiff size={15}/>查看 {execution.changes.length} 个文件的修改</button></div>}<div ref={end}/>
    </> : tab === 'evidence' ? <><p className="review-explainer">搜索、网页读取与工具返回的实际证据快照，已提供给审阅者。</p>{execution.toolEvidence?.length ? execution.toolEvidence.map(item => <button className="evidence-card" key={item.id} onClick={() => setEvidence(item)}><strong>{item.title}</strong><p>{item.text.slice(0, 180)}</p><span className="evidence-locator">{item.locator}</span></button>) : <p className="muted review-explainer">尚未获得执行证据。</p>}</> : <><div className="review-explainer">审阅者只读检查本次修改；有修改建议时交回同一执行者，最多修复 {execution.maxRepairRounds} 轮。</div>{execution.reviews.length ? execution.reviews.map(review => <article className={`review-result verdict-${review.verdict}`} key={review.id}><div className="section-heading"><h3>{review.model.modelId}</h3><span className="phase-tag">{review.round === 0 ? '初审' : `修复后第 ${review.round} 轮`} · {review.verdict === 'pass' ? '通过' : review.verdict === 'changes_requested' ? '建议修改' : '审阅失败'}</span></div><div className="markdown"><Markdown text={review.findings} notify={notify}/></div></article>) : <p className="muted review-explainer">{execution.reviewers.length ? '执行结束后将开始独立审阅。' : '这次任务未配置审阅模型。'}</p>}</> }</div>
    <div className="terminal-area"><button className="terminal-toggle" aria-expanded={terminalOpen} onClick={() => setTerminalOpen(v => !v)}><Terminal size={15}/>命令输出 <span>{commandEvents.length}</span><ChevronRight size={14} className={terminalOpen ? 'rotate' : ''}/></button>{terminalOpen && <div className="terminal-output">{commandEvents.length ? commandEvents.map(e => <pre key={e.id}><strong>{e.tool} · {e.state}</strong>{'\n'}{e.text}</pre>) : <p>尚未运行命令。</p>}</div>}</div>
  </section><aside className="execution-sidebar"><div className="side-tabs"><button className={side === 'changes' ? 'active' : ''} onClick={() => setSide('changes')}>修改 <span>{execution.changes.length}</span></button><button className={side === 'files' ? 'active' : ''} onClick={() => setSide('files')}>项目文件</button></div>{side === 'files' ? <ProjectFiles key={execution.projectId} projectId={execution.projectId} initialPath={path} refreshKey={active ? '' : execution.updatedAt} notify={notify}/> : <div className="changes-panel">{execution.changes.length ? execution.changes.map(change => <details className="change-file" key={change.path} open={execution.changes.length === 1}><summary><span className={`change-kind ${change.kind}`}>{change.kind === 'added' ? '+' : change.kind === 'deleted' ? '−' : 'M'}</span><span title={change.path}>{change.path}</span></summary><button className="text-button" disabled={change.kind === 'deleted'} onClick={() => { setPath(change.path); setSide('files') }}>查看当前文件 →</button>{change.diff ? <pre className="diff-view">{change.diff.split('\n').map((line, i) => <span key={i} className={line.startsWith('+') ? 'diff-added' : line.startsWith('-') ? 'diff-removed' : line.startsWith('@@') ? 'diff-range' : ''}>{line}{'\n'}</span>)}</pre> : <p className="muted small">{change.binary ? '二进制文件已变更，请查看产物。' : '没有可显示的文本差异。'}</p>}</details>) : <div className="side-empty"><FileDiff size={28}/><p>暂时没有文件修改</p><span>实际变更会在执行后显示；已有文件保持在项目目录中。</span></div>}</div>}</aside>{evidence && <EvidenceDetail evidence={evidence} onClose={() => setEvidence(null)} notify={notify}/>}</div>
}

function Markdown({ text, notify }: { text: string; notify: Notify }) { return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ a: ({ href, children }) => <a href={href} onClick={e => { e.preventDefault(); if (href) void api.openExternal(href).catch(err => notify(String(err), true)) }}>{children}</a>, img: ({ alt }) => <span>[图片：{alt}]</span> }}>{text}</ReactMarkdown> }
