import { useState } from 'react'
import { BookOpen, Plus, Upload, Link, Search, FileText, Trash2, ExternalLink, X, RefreshCw, CheckCircle2, CircleAlert, Image, Film, Music, FileSpreadsheet } from 'lucide-react'
import type { Bootstrap, Evidence, KnowledgeBase, ModelRef, Source } from '../../shared/types'
import { api } from './api'
import { Empty, Modal, ModelSelect, Spinner, modelName, useTask, type Confirm, type Notify } from './common'

const sourceStatus = { queued: '等待处理', processing: '处理中', ready: '可用于讨论', failed: '导入失败', cancelled: '已取消' }
function SourceIcon({ source }: { source: Source }) { const name = source.title.toLowerCase(); if (/\.(png|jpg|jpeg|webp|gif|bmp)$/.test(name)) return <Image size={19}/>; if (/\.(mp4|mkv|mov|webm|avi)$/.test(name)) return <Film size={19}/>; if (/\.(mp3|wav|m4a|ogg|flac)$/.test(name)) return <Music size={19}/>; if (/\.(xlsx|xls|csv)$/.test(name)) return <FileSpreadsheet size={19}/>; return source.url ? <Link size={19}/> : <FileText size={19}/> }

export function EvidenceDetail({ evidence, onClose, notify }: { evidence: Evidence; onClose: () => void; notify: Notify }) {
  const { busy, run } = useTask(notify)
  return <Modal title="证据原文" onClose={onClose}><div className="evidence-detail"><div className="eyebrow">{evidence.kind === 'vision' ? '模型画面描述' : evidence.kind === 'ocr' ? '识别文字' : evidence.kind === 'transcript' ? '音视频转录' : evidence.kind === 'web' ? '网络搜索' : evidence.kind === 'tool' ? '工具结果（非网页引用）' : '文档摘录'}</div><h3>{evidence.title}</h3><p className="muted small">{evidence.locator} · {new Date(evidence.retrievedAt).toLocaleString('zh-CN')}</p>{evidence.query && <p className="muted small">搜索查询：{evidence.query}</p>}<pre className="evidence-text">{evidence.text}</pre><div className="small muted">证据编号：{evidence.id}</div></div><div className="modal-footer"><span/>{evidence.sourceId && <button disabled={busy} onClick={() => void run(() => api.openSource({ sourceId: evidence.sourceId!, locator: evidence.locator }))}><ExternalLink size={15}/>打开原始资料</button>}{evidence.url && <button className="primary" disabled={busy} onClick={() => void run(() => api.openExternal(evidence.url!))}><ExternalLink size={15}/>打开来源网页</button>}</div></Modal>
}

export function KnowledgeView({ data, refresh, notify, confirm }: { data: Bootstrap; refresh: () => Promise<void>; notify: Notify; confirm: Confirm }) {
  const [selectedId, setSelectedId] = useState(data.knowledgeBases[0]?.id ?? '')
  const selected = data.knowledgeBases.find(k => k.id === selectedId) ?? data.knowledgeBases[0]
  const [editing, setEditing] = useState<KnowledgeBase | 'new' | null>(null)
  const [url, setUrl] = useState('')
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<Evidence[] | null>(null)
  const [chunks, setChunks] = useState<{ title: string; items: Evidence[] } | null>(null)
  const [evidence, setEvidence] = useState<Evidence | null>(null)
  const { busy, run } = useTask(notify)
  const sources = data.sources.filter(s => s.knowledgeBaseId === selected?.id)
  const hasModels = data.providers.some(p => p.modelIds.length)
  return <div className="page knowledge-page"><header className="page-heading"><div><div className="eyebrow">A SHARED GROUND FOR BETTER THINKING</div><h1>让讨论有据可依</h1><p>资料只需导入一次，就能在不同讨论中共同参考。</p></div><button className="primary" disabled={!hasModels} onClick={() => setEditing('new')}><Plus size={17}/>新建知识库</button></header>
    {!data.knowledgeBases.length ? <Empty icon={<BookOpen size={32}/>} title="你的第一个知识库" action={hasModels ? <button className="primary" onClick={() => setEditing('new')}><Plus size={16}/>创建知识库</button> : undefined}>{hasModels ? '为一个主题收集文档、网页、图片和音视频。选择 Embedding 模型后，就可以开始导入。' : '先在设置中添加模型服务，并加入 Embedding 模型 ID，再创建你的资料集合。'}</Empty> : <>
      <div className="knowledge-tabs" role="tablist" aria-label="知识库">{data.knowledgeBases.map(k => <button role="tab" aria-selected={selected?.id === k.id} key={k.id} className={selected?.id === k.id ? 'active' : ''} onClick={() => { setSelectedId(k.id); setResults(null); setQuery('') }}><BookOpen size={15}/>{k.name}<span>{data.sources.filter(s => s.knowledgeBaseId === k.id && s.status === 'ready').length}</span></button>)}</div>
      {selected && <><div className="knowledge-summary"><div><h2>{selected.name}</h2><p className="small muted">{modelName(selected.embedding, data.providers)} · {selected.dimensions ? `${selected.dimensions} 维` : '尚未建立索引'} · {sources.filter(s => s.status === 'ready').length} 份就绪资料</p></div><div className="button-group"><button disabled={busy} onClick={() => setEditing(selected)}><RefreshCw size={15}/>重建索引</button><button className="icon-button danger-hover" aria-label="删除知识库" disabled={busy} onClick={() => void run(async () => { if (await confirm('删除知识库', `删除“${selected.name}”中的所有资料和索引。已保存在会话中的证据摘录仍会保留。`)) { await api.deleteKnowledgeBase(selected.id); setResults(null); await refresh() } })}><Trash2 size={17}/></button></div></div>
      <div className="import-panel"><div className="upload-icon"><Upload size={24}/></div><div className="import-description"><h3>把资料带到桌上</h3><p>PDF · Word · 文本 · 图片 · Excel · 音频 · 视频</p><span className="small muted">扫描和图片需要视觉模型；音频需要转录模型。</span></div><button className="primary" disabled={busy} onClick={() => void run(async () => { const paths = await api.selectFiles(); if (paths.length) { await api.importSources({ knowledgeBaseId: selected.id, filePaths: paths }); await refresh(); notify('资料已加入导入队列') } })}><Plus size={16}/>选择文件</button></div>
      {!data.mediaReady && <p className="form-hint">音视频处理组件尚未就绪；文档和图片导入仍可使用。</p>}
      <form className="inline-input url-import" onSubmit={e => { e.preventDefault(); void run(async () => { await api.importSources({ knowledgeBaseId: selected.id, url: url.trim() }); setUrl(''); await refresh(); notify('网页已加入导入队列') }) }}><Link size={17}/><input aria-label="导入网页地址" type="url" required placeholder="或粘贴网页地址，保存正文与来源…" value={url} onChange={e => setUrl(e.target.value)}/><button disabled={busy || !url.trim()}>导入网页</button></form>
      <div className="section-heading"><h3>资料 <span className="muted">{sources.length}</span></h3><span className="small muted">只有处理完成的资料会参与讨论</span></div>
      <div className="source-list">{sources.length ? sources.map(source => <article className="source-row" key={source.id}><div className={`source-icon ${source.status}`}><SourceIcon source={source}/></div><div className="source-main"><button className="source-title" disabled={busy || source.status !== 'ready'} title={source.title} onClick={() => void run(async () => setChunks({ title: source.title, items: await api.getSourceChunks(source.id) }))}>{source.title}</button><p className={source.status === 'failed' ? 'error-text' : 'muted'}>{source.error || source.progress || sourceStatus[source.status]}{source.status === 'ready' ? ` · ${source.chunkCount} 个片段` : ''}</p></div><span className={`source-status ${source.status}`}>{source.status === 'ready' ? <CheckCircle2 size={13}/> : source.status === 'failed' ? <CircleAlert size={13}/> : null}{sourceStatus[source.status]}</span>{source.status === 'queued' || source.status === 'processing' ? <button aria-label={`取消导入 ${source.title}`} className="icon-button" disabled={busy} onClick={() => void run(async () => { await api.cancelImport(source.id); await refresh() })}><X size={16}/></button> : <button aria-label={`删除资料 ${source.title}`} className="icon-button danger-hover" disabled={busy} onClick={() => void run(async () => { if (await confirm('删除资料', `删除“${source.title}”及其索引片段。历史会话保留已使用的证据摘录。`)) { await api.deleteSource(source.id); await refresh() } })}><Trash2 size={16}/></button>}</article>) : <div className="inline-empty">还没有资料。选择文件或导入一个网页开始。</div>}</div>
      <section className="retrieval-panel"><div className="section-heading"><h3><Search size={17}/>试试知识库检索</h3></div><form className="inline-input" onSubmit={e => { e.preventDefault(); void run(async () => setResults(await api.searchKnowledge({ knowledgeBaseIds: [selected.id], query: query.trim() }))) }}><input aria-label="知识库检索问题" placeholder="用自然语言提问，检查能找到哪些相关资料…" value={query} onChange={e => setQuery(e.target.value)} required/><button disabled={busy || !query.trim() || !sources.some(s => s.status === 'ready')}>{busy ? <Spinner/> : <><Search size={16}/>检索</>}</button></form>{results && <div className="retrieval-results">{results.length ? results.map(item => <button className="retrieval-result" key={item.id} onClick={() => setEvidence(item)}><strong>{item.title}</strong><span className="small muted">{item.locator}</span><p>{item.text.slice(0, 220)}</p></button>) : <p className="muted">没有找到相关片段。检查资料导入状态或尝试换个问法。</p>}</div>}</section>
      </>}
    </>}
    {editing && <KnowledgeEditor data={data} knowledge={editing === 'new' ? undefined : editing} notify={notify} onClose={() => setEditing(null)} onSaved={async id => { await refresh(); setSelectedId(id); setResults(null); setEditing(null) }}/>}
    {chunks && !evidence && <Modal title={chunks.title} wide onClose={() => setChunks(null)}><p className="muted small">索引中的资料片段 · 点击查看原文与来源位置</p><div className="chunk-list">{chunks.items.length ? chunks.items.map(c => <button className="retrieval-result" key={c.id} onClick={() => setEvidence(c)}><strong>{c.locator}</strong><p>{c.text.slice(0, 350)}</p></button>) : <p className="muted">该资料暂时没有可用片段。</p>}</div></Modal>}
    {evidence && <EvidenceDetail evidence={evidence} onClose={() => setEvidence(null)} notify={notify}/>}
  </div>
}

function KnowledgeEditor({ data, knowledge, onClose, onSaved, notify }: { data: Bootstrap; knowledge?: KnowledgeBase; onClose: () => void; onSaved: (id: string) => Promise<void>; notify: Notify }) {
  const [name, setName] = useState(knowledge?.name ?? '')
  const [embedding, setEmbedding] = useState<ModelRef | undefined>(knowledge?.embedding)
  const { busy, run } = useTask(notify)
  return <Modal title={knowledge ? '重建知识库索引' : '新建知识库'} onClose={onClose}><form onSubmit={e => { e.preventDefault(); void run(async () => { if (!embedding) return; if (knowledge) { await api.rebuildKnowledgeBase({ id: knowledge.id, embedding }); await onSaved(knowledge.id); notify('已开始重建索引') } else { const k = await api.createKnowledgeBase({ name: name.trim(), embedding }); await onSaved(k.id); notify('知识库已创建，现在可以添加资料') } }) }}><label className="field"><span>知识库名称</span><input autoFocus required disabled={Boolean(knowledge)} value={name} onChange={e => setName(e.target.value)} placeholder="例如：产品研究资料"/></label><ModelSelect required providers={data.providers} label="Embedding 模型" value={embedding} onChange={setEmbedding}/><div className="info-note"><BookOpen size={18}/><p>{knowledge ? '重建将清除当前向量索引，并重新处理原始资料。完成之前，这些资料不能用于新讨论。会话中已有的证据保留。' : '请选择支持 Embeddings 接口的向量模型。一个知识库始终使用同一个模型及向量维度。模型列表中没有时，可先到设置中手动添加其 ID。'}</p></div><div className="modal-footer"><span/><button type="button" onClick={onClose}>取消</button><button disabled={busy || !embedding || !name.trim()} className="primary">{busy ? <Spinner/> : knowledge ? '确认重建' : '创建知识库'}</button></div></form></Modal>
}
