import { useEffect, useRef, useState } from 'react'
import { Plus, Server, Trash2, Check, PlugZap, Search, Save, KeyRound, ArrowRight, ShieldCheck, RefreshCw, LogIn, Globe2 } from 'lucide-react'
import type { Bootstrap, Provider, ProviderInput, SettingsInput, Evidence } from '../../shared/types'
import { api, errorText } from './api'
import { DEFAULT_SEARCH } from '../../shared/workspace'
import type { AgentRuntimeStatus, AgentKind } from '../../shared/execution'
import { Empty, ModelSelect, Modal, Spinner, useTask, type Confirm, type Notify } from './common'
import { RecoveryPanel } from './RecoveryPanel'
import { EditorSettings } from './EditorIntegration'
import { CollapseGroup, CollapseControls, Collapsible } from './Collapsible'
import { NetworkSelect, networkLabel, useNetwork } from './NetworkContext'

export function SettingsView({ data, refresh, notify, confirm }: { data: Bootstrap; refresh: () => Promise<void>; notify: Notify; confirm: Confirm }) {
  const network = useNetwork()
  const [editing, setEditing] = useState<Provider | 'new' | null>(null)
  const [settings, setSettings] = useState<SettingsInput>({ moderator: data.settings.moderator, vision: data.settings.vision, transcription: data.settings.transcription, search: data.settings.search ?? { ...DEFAULT_SEARCH } })
  const [searchResults, setSearchResults] = useState<Evidence[]>([])
  const [actionError, setActionError] = useState('')
  const { busy, run: task } = useTask((text, error) => { if (error) setActionError(text); notify(text, error) })
  const run = (action: () => Promise<void>) => { setActionError(''); return task(action) }
  const settingsDirty = JSON.stringify(settings) !== JSON.stringify({ moderator: data.settings.moderator, vision: data.settings.vision, transcription: data.settings.transcription, search: data.settings.search ?? { ...DEFAULT_SEARCH } })
  return <CollapseGroup><div className="page settings-page"><header className="page-heading"><div><div className="eyebrow">YOUR MODELS, YOUR CHOICE</div><h1>连接你的模型</h1><p>一个服务地址，多种思考方式。密钥加密保存在本机。</p></div><button className="primary" onClick={() => setEditing('new')}><Plus size={17}/>添加模型服务</button></header><CollapseControls/>
    <Collapsible id="settings.providers" className="settings-section" defaultOpen title={<><Server size={19}/>模型服务</>} summary={`${data.providers.length} 个服务 · ${data.providers.reduce((count, provider) => count + provider.modelIds.length, 0)} 个模型`}>
      {!data.providers.length ? <Empty icon={<PlugZap size={30}/>} title="从连接第一个服务开始" action={<button onClick={() => setEditing('new')} className="primary">添加服务 <ArrowRight size={16}/></button>}>支持 DeepSeek、Kimi 等 OpenAI 兼容接口。填入地址和密钥，再选择要加入讨论的模型。</Empty> : <div className="provider-grid">{data.providers.map(p => <article className="provider-card" key={p.id}><div className="provider-heading"><div className="service-avatar">{p.name.slice(0, 1).toUpperCase()}</div><div><h3>{p.name}</h3><span className="muted tiny">{p.kind && p.kind !== 'api' ? (p.kind === 'claude' && p.claudeAuth === 'apiKey' ? p.hasKey ? 'Claude Code · API Key 已保存' : 'Claude Code · 未配置 API Key' : `${p.kind === 'codex' ? 'Codex' : 'Claude Code'} 官方登录`) : p.hasKey ? '密钥已加密保存' : '未设置密钥'}</span></div><button className="icon-button danger-hover" aria-label={`删除服务 ${p.name}`} disabled={busy} onClick={() => void run(async () => { if (await confirm('删除模型服务', `删除“${p.name}”及保存的密钥。引用此服务的会话和知识库需要重新配置。`)) { await api.removeProvider(p.id); await refresh() } })}><Trash2 size={16}/></button></div><p className="service-url" title={p.baseUrl}>{p.baseUrl || '通过官方 Agent 运行时连接'}</p><p className="provider-network-label"><Globe2 size={13}/>{networkLabel(p.network, network?.state)}</p><div className="model-chips">{p.modelIds.slice(0, 4).map(m => <span key={m}>{m}</span>)}{p.modelIds.length > 4 && <span>+{p.modelIds.length - 4}</span>}{!p.modelIds.length && <span>尚未添加模型</span>}</div><button className="text-button" onClick={() => setEditing(p)}>管理服务与模型 <ArrowRight size={14}/></button></article>)}</div>}
    </Collapsible>
    <div className="settings-network-entry"><div><h3>网络与订阅</h3><p>导入兼容订阅，让不同模型服务分别使用直连或指定节点。</p></div><button onClick={() => network?.openSettings()}><Globe2 size={16}/>管理网络 <ArrowRight size={14}/></button></div>
    <AgentRuntimes notify={notify}/>
    <RecoveryPanel refresh={refresh} notify={notify}/>
    <EditorSettings notify={notify}/>
    <form className="settings-capability-form" onSubmit={e => { e.preventDefault(); void run(async () => { await api.saveSettings(settings); await refresh(); setSettings(s => ({ ...s, tavilyKey: undefined })); notify('设置已保存') }) }}><Collapsible id="settings.capabilities" className="settings-section" title="专用能力" summary={<><span>可以选择同一个服务下的不同模型</span>{settingsDirty && <span className="network-status failed">未保存</span>}{actionError && <span className="network-status failed">设置需要处理</span>}</>}>
      <div className="form-grid"><ModelSelect label="默认主持 / 裁判模型" providers={data.providers} value={settings.moderator} onChange={moderator => setSettings(s => ({ ...s, moderator }))}/><ModelSelect label="视觉模型（图片和扫描页）" providers={data.providers} value={settings.vision} onChange={vision => setSettings(s => ({ ...s, vision }))}/><ModelSelect label="转录模型（音频和视频）" providers={data.providers} value={settings.transcription} onChange={transcription => setSettings(s => ({ ...s, transcription }))}/></div>
      </Collapsible><Collapsible id="settings.search" className="settings-section" title={<><Globe2 size={17}/>联网搜索</>} summary={<><span>{settings.search?.provider === 'tavily' ? 'Tavily API' : settings.search?.provider === 'searxng' ? 'SearXNG' : '浏览器搜索 · 无需 API Key'}{busy ? ' · 正在处理…' : ''}</span>{settingsDirty && <span className="network-status failed">未保存</span>}{actionError && <span role="alert" className="panel-error">{actionError}</span>}</>}><div className="form-grid"><label className="field"><span>搜索方式</span><select aria-label="搜索方式" value={settings.search?.provider ?? 'browser'} onChange={e => setSettings(s => ({ ...s, search: { ...(s.search ?? DEFAULT_SEARCH), provider: e.target.value as 'browser' | 'tavily' | 'searxng' } }))}><option value="browser">浏览器搜索 · 无需 API Key</option><option value="tavily">Tavily API</option><option value="searxng">SearXNG · 自部署</option></select></label>{(!settings.search || settings.search.provider === 'browser') && <label className="field"><span>搜索引擎</span><select aria-label="搜索引擎" value={settings.search?.engine ?? 'bing'} onChange={e => setSettings(s => ({ ...s, search: { ...(s.search ?? DEFAULT_SEARCH), engine: e.target.value as 'bing' | 'baidu' | 'google' } }))}><option value="bing">Bing</option><option value="baidu">百度</option><option value="google">Google</option></select></label>}{settings.search?.provider === 'searxng' && <label className="field"><span>SearXNG 地址</span><input aria-label="SearXNG 地址" type="url" required placeholder="https://search.example.com" value={settings.search.searxngUrl ?? ''} onChange={e => setSettings(s => ({ ...s, search: { ...(s.search ?? DEFAULT_SEARCH), searxngUrl: e.target.value } }))}/></label>}</div>
      <label className="field"><span>Tavily 搜索密钥</span><input type="password" autoComplete="off" placeholder={data.settings.hasTavilyKey ? '已保存 · 留空保持不变' : 'tvly-…'} value={settings.tavilyKey ?? ''} onChange={e => setSettings(s => ({ ...s, tavilyKey: e.target.value || undefined }))}/></label>
      <p className="muted small search-description">{settings.search?.provider === 'searxng' ? '实例需开启 JSON 输出。会明确显示请求失败或结果正文无法获取。' : settings.search?.provider === 'tavily' ? '使用上方保存的 Tavily 密钥；实际额度与费用由 Tavily 提供。' : '使用本机浏览器页面获取结果。遇到验证页面会提示处理，未获得的证据不会被当作搜索成功。'}</p><button type="button" disabled={busy} onClick={() => void run(async () => { setSearchResults([]); await api.saveSettings(settings); await refresh(); setSearchResults(await api.searchWeb('人工智能 开源 研究')); notify('搜索已返回实际结果') })}><Search size={15}/>保存并测试搜索</button>
      {searchResults.length > 0 && <div className="search-test-results">{searchResults.slice(0, 3).map(result => <button type="button" key={result.id} onClick={() => result.url && void api.openExternal(result.url).catch(e => notify(errorText(e), true))}><strong>{result.title}</strong><span>{result.contentType === 'snippet' ? '摘要' : '正文'} · {result.text.slice(0, 100)}</span></button>)}</div>}
      </Collapsible><div className="settings-footer"><p className="small muted"><ShieldCheck size={16}/>能力由你明确指定；应用不会根据模型名称猜测。</p><button className="primary" disabled={busy}>{busy ? <Spinner/> : <><Save size={16}/>保存设置</>}</button></div>
    </form>
    <div className="info-note"><KeyRound size={17}/><div><strong>数据留在本机，调用由你掌控</strong><p>讨论记录和资料保存在本机。使用模型、搜索和资料处理时，相关内容会发送到你配置的服务；费用由对应服务收取。</p></div></div>
    {editing && <ProviderEditor key={typeof editing === 'string' ? editing : editing.id} provider={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} refresh={refresh} notify={notify}/>}
  </div></CollapseGroup>
}

function AgentRuntimes({ notify }: { notify: Notify }) {
  const [statuses, setStatuses] = useState<AgentRuntimeStatus[]>([])
  const [error, setError] = useState('')
  const [pending, setPending] = useState<AgentKind | null>(null)
  const [claudeLogin, setClaudeLogin] = useState(false)
  const [claudeMethod, setClaudeMethod] = useState<'subscription' | 'console'>('subscription')
  const load = () => api.agentStatus().then(value => { setStatuses(value); setError('') }).catch(e => setError(errorText(e)))
  useEffect(() => { void load() }, [])
  const act = async (kind: AgentKind, action: 'prepare' | 'login' | 'logout' | 'open') => {
    setPending(kind); setError('')
    try {
      if (action === 'prepare') { const status = await api.agentPrepare(kind); notify(status.message) }
      else if (action === 'open') { const result = await api.agentOpenClaude(); notify(result.message) }
      else if (kind !== 'api' && action === 'login') { const result = await api.agentLogin(kind === 'codex' ? { kind } : { kind, method: claudeMethod }); setClaudeLogin(false); notify(result.message); if (result.url) await api.openExternal(result.url) }
      else if (kind !== 'api') { await api.agentLogout(kind); notify('账号已退出') }
      await load()
    } catch (e) { setError(errorText(e)) } finally { setPending(null) }
  }
  return <><Collapsible id="settings.runtimes" className="settings-section" title="执行环境与官方账号" summary={<>{pending ? '正在处理…' : `${statuses.filter(status => status.available).length} / 3 个环境已就绪`}{error && <span role="alert" className="panel-error">{error}</span>}</>} actions={<button type="button" disabled={!!pending} onClick={() => void load()}><RefreshCw size={14}/>刷新状态</button>}><p className="muted small section-description">API 模型使用应用准备的执行环境；官方账号通过对应运行时登录。Claude Code 也可在模型服务中使用自己的 Anthropic API Key。</p>{error && <p role="alert" className="panel-error">{error}</p>}<div className="runtime-grid">{(['api', 'codex', 'claude'] as const).map(kind => {
    const status = statuses.find(s => s.kind === kind)
    return <article className="runtime-card" key={kind}><strong>{kind === 'api' ? 'API 执行环境' : kind === 'codex' ? 'Codex' : 'Claude Code'}</strong><span className="runtime-state">{status ? status.available ? kind === 'api' ? '环境已就绪' : status.authenticated === true ? '官方认证已就绪' : status.authenticated === false ? '官方账号未登录' : '认证状态待确认' : '环境未就绪' : '正在读取状态…'}</span><p>{status?.message ?? '正在检测本机环境'}</p>{status?.version && <small>{status.version}</small>}<div className="button-group"><button disabled={!!pending} onClick={() => void act(kind, 'prepare')}>{pending === kind ? <Spinner text="处理中…"/> : '准备环境'}</button>{kind === 'codex' && <button disabled={!!pending || !status?.available} onClick={() => void act(kind, status?.authenticated ? 'logout' : 'login')}><LogIn size={14}/>{status?.authenticated ? '退出账号' : '登录账号'}</button>}{kind === 'claude' && <><button disabled={!!pending || !status?.available} onClick={() => setClaudeLogin(true)}><LogIn size={14}/>设置官方登录</button>{status?.authenticated && <button disabled={!!pending} onClick={() => void act(kind, 'logout')}>退出官方账号</button>}</>}</div>{kind === 'claude' && <details className="advanced"><summary>官方终端与认证说明</summary><p className="muted small">打开原版 Claude Code，在官方界面中使用 /login 或 /config。它沿用本应用的账号目录；终端由你操作，关闭后刷新状态。自有 API Key 请在对应模型服务中设置。</p><button type="button" disabled={!!pending || !status?.available} onClick={() => void act('claude', 'open')}>打开原版 Claude Code</button><p className="muted tiny">使用你自己的账号或 Key，由 Anthropic 直接计费。<a href="https://code.claude.com/docs/en/legal-and-compliance" onClick={event => { event.preventDefault(); void api.openExternal(event.currentTarget.href).catch(error => notify(errorText(error), true)) }}>官方使用条款</a></p></details>}</article>
  })}</div></Collapsible>{claudeLogin && <Modal title="设置 Claude Code 官方登录" onClose={() => { if (!pending) setClaudeLogin(false) }}><label className="field"><span>官方认证方式</span><select aria-label="Claude 官方认证方式" value={claudeMethod} disabled={!!pending} onChange={event => setClaudeMethod(event.target.value as typeof claudeMethod)}><option value="subscription">Claude 订阅账号</option><option value="console">Anthropic Console · API 用量计费</option></select></label><p className="muted small">{claudeMethod === 'subscription' ? '通过原版 Claude Code 的官方流程登录自己的 Claude 账号。' : '通过原版 Claude Code 登录自己的 Anthropic Console；API 用量与 Claude 订阅分别计费。'}登录信息由官方 CLI 管理，不复制到模型服务。</p><div className="modal-footer"><button disabled={!!pending} onClick={() => setClaudeLogin(false)}>取消</button><button className="primary" disabled={!!pending} onClick={() => void act('claude', 'login')}>{pending ? <Spinner text="正在启动…"/> : '打开官方登录'}</button></div></Modal>}</>
}

export function ProviderEditor({ provider, onClose, refresh, notify }: { provider?: Provider; onClose: () => void; refresh: () => Promise<void>; notify: Notify }) {
  const network = useNetwork()
  const fields = useRef<HTMLDivElement>(null)
  const [form, setForm] = useState<ProviderInput>(provider ? { id: provider.id, kind: provider.kind ?? 'api', ...(provider.kind === 'claude' ? { claudeAuth: provider.claudeAuth ?? 'official' } : {}), name: provider.name, baseUrl: provider.baseUrl, modelIds: provider.modelIds, tokenParameter: provider.tokenParameter, streamUsage: provider.streamUsage, timeoutMs: provider.timeoutMs, network: provider.network ?? { mode: 'system' } } : { kind: 'api', name: '', baseUrl: '', modelIds: [], tokenParameter: 'max_tokens', streamUsage: false, timeoutMs: 120000, network: { mode: 'system' } })
  const [hasSavedKey, setHasSavedKey] = useState(provider?.hasKey ?? false)
  const [discovered, setDiscovered] = useState<string[]>(provider?.modelIds ?? [])
  const [manual, setManual] = useState('')
  const [filter, setFilter] = useState('')
  const visibleModels = discovered.filter(id => id.toLowerCase().includes(filter.trim().toLowerCase()))
  const [testResult, setTestResult] = useState('')
  const [testId, setTestId] = useState(provider?.modelIds[0] ?? '')
  const [structuredMode, setStructuredMode] = useState<'json_object' | 'json_schema'>('json_schema')
  const [savedForm, setSavedForm] = useState(form)
  const [actionError, setActionError] = useState('')
  const { busy, run: task } = useTask((text, error) => { if (error) setActionError(text); notify(text, error) })
  const run = (action: () => Promise<void>) => { setActionError(''); return task(action) }
  const dirty = JSON.stringify(form) !== JSON.stringify(savedForm)
  const update = <K extends keyof ProviderInput>(key: K, value: ProviderInput[K]) => setForm(f => ({ ...f, [key]: value }))
  const save = async () => {
    for (const field of fields.current?.querySelectorAll<HTMLInputElement | HTMLSelectElement>('input, select') ?? []) {
      if (!field.checkValidity()) { field.reportValidity(); throw new Error(field.validationMessage || '请检查连接信息') }
    }
    const saved = await api.saveProvider(form); setForm(f => ({ ...f, id: saved.id, apiKey: undefined })); setHasSavedKey(saved.hasKey); setSavedForm({ ...form, id: saved.id, apiKey: undefined }); await refresh(); await network?.refresh().catch(() => {}); return saved }
  const native = form.kind === 'codex' || form.kind === 'claude'
  const claudeKey = form.kind === 'claude' && form.claudeAuth === 'apiKey'
  const valid = form.name.trim() && (native || /^https?:\/\//.test(form.baseUrl))
  return <Modal title={provider ? '管理模型服务' : '添加模型服务'} onClose={onClose} wide><CollapseGroup><div ref={fields}><CollapseControls/><div className="wizard-steps"><span className="active">1 <b>连接服务</b></span><i/><span className={form.id ? 'active' : ''}>2 <b>选择模型</b></span><i/><span className={testResult ? 'active' : ''}>3 <b>测试连接</b></span></div>
    <Collapsible id={`provider.${provider?.id ?? 'new'}.connection`} title="连接信息" defaultOpen={!provider} summary={<><span>{form.name || '填写服务地址与账号'}</span>{dirty && <span className="network-status failed">未保存</span>}{actionError && <span role="alert" className="panel-error">{actionError}</span>}</>}>
    <label className="field"><span>接入类型</span><select aria-label="接入类型" value={form.kind ?? 'api'} onChange={e => { const kind = e.target.value as 'api' | 'codex' | 'claude'; setHasSavedKey(false); setForm(f => ({ ...f, kind, claudeAuth: kind === 'claude' ? 'official' : undefined, apiKey: undefined, baseUrl: kind === 'api' ? f.baseUrl : '', name: f.name || (kind === 'codex' ? 'Codex 账号' : kind === 'claude' ? 'Claude Code' : '') })); setTestResult('') }}><option value="api">OpenAI 兼容 API / 自建网关</option><option value="codex">Codex 官方账号</option><option value="claude">Claude Code</option></select></label>
    {form.kind === 'claude' && <label className="field"><span>Claude Code 认证方式</span><select aria-label="Claude Code 认证方式" value={form.claudeAuth ?? 'official'} onChange={event => { setForm(value => ({ ...value, claudeAuth: event.target.value as 'official' | 'apiKey', apiKey: undefined })); setTestResult('') }}><option value="official">官方登录 · 订阅或 Console</option><option value="apiKey">自有 Anthropic API Key</option></select></label>}
    {!native && !form.id && <div className="provider-presets"><span>快速填写</span>{[{ name: 'DeepSeek', baseUrl: 'https://api.deepseek.com', docs: 'https://api-docs.deepseek.com/' }, { name: 'Kimi（国际站）', baseUrl: 'https://api.moonshot.ai/v1', docs: 'https://platform.kimi.ai/docs/overview' }].map(preset => <button key={preset.name} type="button" onClick={() => { setForm(f => ({ ...f, name: preset.name, baseUrl: preset.baseUrl, modelIds: [], apiKey: undefined })); setDiscovered([]); setTestId(''); setTestResult('') }}>{preset.name}</button>)}<span className="muted tiny">填入自己的 Key，再获取实时模型列表</span></div>}
    {native && <div className="info-note"><LogIn size={18}/><p>{claudeKey ? '准备 Claude Code 运行环境后，使用本服务自己的 Anthropic API Key，无需登录订阅账号。按 API 用量计费；缺少或失效的 Key 不会回退到订阅。保存密钥不代表已验证，请主动测试连接。' : '通过本机官方 Agent 调用。先在运行环境卡片完成准备和官方登录，然后获取模型或填写官方模型 ID。Claude Code 的订阅与 Console 认证由原版 CLI 管理。'}</p></div>}
    <div className="form-grid"><label className="field"><span>服务名称</span><input required placeholder="例如：DeepSeek" value={form.name} onChange={e => update('name', e.target.value)}/></label>{!native && <label className="field"><span>API 地址</span><input type="url" required placeholder="https://api.deepseek.com" value={form.baseUrl} onChange={e => update('baseUrl', e.target.value.trim())}/></label>}{(!native || claudeKey) && <label className="field full"><span>{claudeKey ? 'Anthropic API Key' : 'API 密钥'}</span><input type="password" autoComplete="off" placeholder={hasSavedKey ? '已保存的密钥将保留；填写可替换' : claudeKey ? '填写自己的 Anthropic API Key' : '填写服务提供的密钥（本地服务可留空）'} value={form.apiKey ?? ''} onChange={e => update('apiKey', e.target.value || undefined)}/></label>}</div>
    {claudeKey && <div className="selection-toolbar"><span className="muted small">{form.apiKey === '' ? '保存后移除密钥；不会改用官方账号' : form.apiKey ? '新密钥尚未保存' : hasSavedKey ? '密钥已加密保存；可用性以连接测试为准' : '尚未配置密钥'}</span>{hasSavedKey && <button type="button" disabled={busy} onClick={() => update('apiKey', form.apiKey === '' ? undefined : '')}>{form.apiKey === '' ? '撤销移除' : '移除已保存密钥'}</button>}</div>}
    <details className="advanced"><summary>高级连接设置</summary><div className="form-grid"><label className="field"><span>输出长度参数</span><select value={form.tokenParameter} onChange={e => update('tokenParameter', e.target.value as ProviderInput['tokenParameter'])}><option value="max_tokens">max_tokens</option><option value="max_completion_tokens">max_completion_tokens</option></select></label><label className="field"><span>请求超时（秒）</span><input type="number" min="1" max="900" value={form.timeoutMs / 1000} onChange={e => update('timeoutMs', Number(e.target.value) * 1000)}/></label><label className="check-label full"><input type="checkbox" checked={form.streamUsage} onChange={e => update('streamUsage', e.target.checked)}/>请求流式用量统计（需网关支持）</label></div></details>
    </Collapsible><Collapsible id={`provider.${provider?.id ?? 'new'}.network`} title="网络线路" summary={<>{networkLabel(form.network, network?.state)}{network?.error && <span role="alert" className="panel-error">{network.error}</span>}{network?.state?.pending && <span className="network-status">待应用</span>}</>}>
    <div className="provider-network-row"><NetworkSelect label="服务网络线路" value={form.network} onChange={value => update('network', value)} disabled={busy}/><div><p className="muted tiny">本服务的所有模型共用线路。保存后新任务使用所选设置。</p><button type="button" className="text-button" onClick={() => network?.openSettings()}><Globe2 size={14}/>管理订阅</button></div>{network?.error && <p role="alert" className="panel-error">网络设置读取失败：{network.error}</p>}{network?.state?.pending && <p className="network-pending">有待应用的网络设置，正在运行的任务仍使用原线路。</p>}{native && <p className="muted tiny">账号调用使用此线路；系统浏览器中的登录页面仍使用浏览器网络。</p>}</div>
    </Collapsible>

    <Collapsible id={`provider.${provider?.id ?? 'new'}.models`} title="模型列表" summary={`已选 ${form.modelIds.length} / ${discovered.length} 个模型${busy ? ' · 正在处理…' : ''}`} actions={<button type="button" disabled={busy || !valid} onClick={() => void run(async () => { const saved = await save(); const ids = await api.discoverModels({ providerId: saved.id }); setDiscovered([...new Set([...ids, ...form.modelIds])]); notify(`获取到 ${ids.length} 个模型，请勾选后保存`) })}><Search size={15}/>保存并获取模型</button>}>
    <div className="inline-input"><input aria-label="手动输入模型 ID" value={manual} placeholder="直接输入模型 ID" onChange={e => setManual(e.target.value)}/><button disabled={!manual.trim()} onClick={() => { const id = manual.trim(); setDiscovered(d => [...new Set([...d, id])]); update('modelIds', [...new Set([...form.modelIds, id])]); setTestId(id); setManual('') }}><Plus size={16}/>添加</button></div>
    {discovered.length > 0 && <input className="model-filter" aria-label="筛选模型" placeholder="筛选模型…" value={filter} onChange={e => setFilter(e.target.value)}/>}
    {discovered.length > 0 && <div className="selection-toolbar"><span>已选 {form.modelIds.length} · 当前 {visibleModels.length}</span><button type="button" disabled={!visibleModels.length} onClick={() => { update('modelIds', [...new Set([...form.modelIds, ...visibleModels])]); if (!testId) setTestId(visibleModels[0]) }}>全选当前筛选</button><button type="button" disabled={!form.modelIds.some(id => visibleModels.includes(id))} onClick={() => update('modelIds', form.modelIds.filter(id => !visibleModels.includes(id)))}>取消当前筛选</button></div>}
    <div className="model-options">{visibleModels.map(id => <label className="check-label" key={id}><input type="checkbox" checked={form.modelIds.includes(id)} onChange={e => { update('modelIds', e.target.checked ? [...form.modelIds, id] : form.modelIds.filter(m => m !== id)); if (e.target.checked && !testId) setTestId(id) }}/><span>{id}</span></label>)}{!discovered.length && <p className="muted small">获取服务的模型列表，或手动输入模型 ID。无需修改配置文件。</p>}</div>
    </Collapsible><Collapsible id={`provider.${provider?.id ?? 'new'}.test`} title="连接测试" summary={busy ? '正在处理…' : testResult ? '测试已完成' : '检测模型实际可用性，测试会调用模型'}>
    <div className="test-row"><select aria-label="选择连接测试模型" value={testId} onChange={e => setTestId(e.target.value)}><option value="">选择模型进行测试</option>{form.modelIds.map(id => <option key={id}>{id}</option>)}</select><button disabled={busy || !valid || !form.modelIds.includes(testId)} onClick={() => void run(async () => { setTestResult(''); const saved = await save(); const result = await api.testModel({ providerId: saved.id, modelId: testId }); setTestResult(result.text); notify('模型连接测试通过') })}><PlugZap size={16}/>测试连接</button>{!native && <button disabled={busy || !valid || !form.modelIds.includes(testId)} onClick={() => void run(async () => { setTestResult(''); const saved = await save(); const result = await api.testToolModel({ providerId: saved.id, modelId: testId }); setTestResult(result.text); notify('工具调用能力测试完成') })}>测试执行能力</button>}</div>
    {!native && <div className="test-row"><select aria-label="结构化输出协议" value={structuredMode} onChange={e => setStructuredMode(e.target.value as typeof structuredMode)}><option value="json_schema">JSON Schema</option><option value="json_object">JSON Object</option></select><button disabled={busy || !valid || !form.modelIds.includes(testId)} onClick={() => void run(async () => { setTestResult(''); const saved = await save(); await api.testStructuredModel({ model: { providerId: saved.id, modelId: testId }, mode: structuredMode }); await refresh(); setTestResult(`${testId} 已通过 ${structuredMode} 能力测试，后续结构化任务会使用此协议。`); notify('结构化输出能力已保存') })}>测试并启用结构化输出</button></div>}
    {!native && <p className="muted small">能力测试会调用所选模型一次。未通过测试的模型继续使用文本协议；失败不会自动重试。</p>}
    {testResult && <div className="test-result"><Check size={16}/><span>{testResult}</span></div>}
    </Collapsible><div className="modal-footer"><span className="muted small">已选择 {form.modelIds.length} 个模型</span><button onClick={onClose}>关闭</button><button disabled={busy || !valid} className="primary" onClick={() => void run(async () => { await save(); notify('模型服务已保存'); onClose() })}>{busy ? <Spinner/> : <><Save size={16}/>保存服务</>}</button></div>
  </div></CollapseGroup></Modal>
}
