import { describe, it, expect } from 'vitest'
import { existsSync } from 'node:fs'
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'
import { RuntimeManager } from '../src/main/components/manager'
import { ExtensionInstaller, unzip, type Revision } from '../src/main/extensions/installer'
import { McpConnection } from '../src/main/extensions/connection'
import { command, digest, isolatedEnvironment } from '../src/main/extensions/util'
import type { ExtensionOptions } from '../src/main/extensions/ports'
import type { CatalogEntry } from '../src/shared/extensions'

const cache = resolve('.cache/components-runtime')
it.skipIf(process.platform !== 'win32')('缺组件首次安装先准备再取得租约，失败后也能移除组件', async () => {
  const root = await mkdtemp(join(tmpdir(), 'extension-first-component-')); const source = join(root, 'source'); await mkdir(source); await writeFile(join(source, 'node.exe'), 'controlled-component'); const archive = join(root, 'node.zip'); execFileSync('tar.exe', ['-caf', archive, '-C', source, 'node.exe']); const bytes = await readFile(archive); const hash = (await import('node:crypto')).createHash('sha256').update(bytes).digest('hex'); const manifestPath = join(root, 'manifest.json'); await writeFile(manifestPath, JSON.stringify({ schema: 1, platform: 'win32-x64', components: [{ id: 'node', name: 'fixture', version: '1', executable: 'node.exe', licenses: [], artifacts: [{ filename: 'node.zip', url: 'https://example.org/node.zip', sha256: hash, format: 'zip', destination: '.' }] }] })); const runtime = new RuntimeManager({ manifestPath, cacheDir: join(root, 'cache'), fetch: async () => new Response(bytes) }); const store: any = { getEntity: () => undefined, listEntities: () => [], saveEntity: () => {}, deleteEntity: () => {}, getSecret: async () => '', setSecret: async () => {}, getProject: () => undefined }; const installer = new ExtensionInstaller({ runtime, store, stateDir: root, emit: () => {}, openExternal: async () => {} }); const entry: CatalogEntry = { id: 'test', kind: 'mcp', name: 'test', description: '', version: '1', status: 'active', packages: [{ registryType: 'npm', identifier: 'fixture', version: '1.0.0', transport: { type: 'stdio' } }] }; const directory = join(root, 'extension'); await mkdir(directory); const revision: Revision = { id: 'r', extensionId: 'e', entry, directory, values: {}, secretKeys: [], tools: [] }; await expect(runtime.resolve('node')).rejects.toThrow('component:node'); await expect(installer.install(entry, { kind: 'mcp', id: 'test' }, revision, new AbortController().signal, () => {})).rejects.toThrow('未包含 npm'); expect((await runtime.list())[0].phase).toBe('ready'); await runtime.remove('node'); expect((await runtime.list())[0].phase).toBe('missing')
})
describe.skipIf(!existsSync(join(cache, 'python', 'active.json')) || !existsSync(join(cache, 'uv', 'active.json')))('固定组件支持扩展安装（真实 Python/uv/ZIP）', () => {
  const runtime = new RuntimeManager({ manifestPath: resolve('resources/components/manifest.json'), cacheDir: cache })
  it('官方嵌入式 Python 经 uv 建独立 venv，安装本机 wheel 并执行 console_scripts', async () => {
    const python = await runtime.resolve('python'), uv = await runtime.resolve('uv'); const root = await mkdtemp(join(tmpdir(), '扩展 Python 环境-')); const env = isolatedEnvironment(join(root, 'profile')); const signal = new AbortController().signal
    const wheel = join(root, 'roundtable_fixture-1.0.0-py3-none-any.whl')
    const code = `import zipfile,sys\nz=zipfile.ZipFile(sys.argv[1],'w')\nz.writestr('roundtable_fixture.py','def main():\\n print("独立环境入口成功")\\n')\nz.writestr('roundtable_fixture-1.0.0.dist-info/METADATA','Metadata-Version: 2.1\\nName: roundtable-fixture\\nVersion: 1.0.0\\n')\nz.writestr('roundtable_fixture-1.0.0.dist-info/WHEEL','Wheel-Version: 1.0\\nGenerator: QA\\nRoot-Is-Purelib: true\\nTag: py3-none-any\\n')\nz.writestr('roundtable_fixture-1.0.0.dist-info/entry_points.txt','[console_scripts]\\nfixture = roundtable_fixture:main\\n')\nz.writestr('roundtable_fixture-1.0.0.dist-info/RECORD','')\nz.close()`
    await command(python.executable, ['-I', '-X', 'utf8', '-c', code, wheel], root, env, signal); const venv = join(root, 'venv'); await command(uv.executable, ['venv', '--python', python.executable, venv], root, env, signal); const executable = join(venv, 'Scripts', 'python.exe'); await command(uv.executable, ['pip', 'install', '--python', executable, '--no-index', wheel], root, env, signal)
    const output = await command(executable, ['-I', '-X', 'utf8', '-c', 'import importlib.metadata,sys; pkg,name=sys.argv[1:3]; sys.argv=[name]+sys.argv[3:]; next(e for e in importlib.metadata.distribution(pkg).entry_points if e.group=="console_scripts" and e.name==name).load()()', 'roundtable-fixture', 'fixture'], root, env, signal); expect(output).toContain('独立环境入口成功'); expect(await command(python.executable, ['-I', '-X', 'utf8', '-c', 'import importlib.util; print(importlib.util.find_spec("roundtable_fixture"))'], root, env, signal)).toContain('None')
  }, 30000)
  it('MCPB 校验 Windows manifest/必填配置并展开运行路径；ZIP 越界不能覆盖目录外文件', async () => {
    const python = await runtime.resolve('python'); const root = await mkdtemp(join(tmpdir(), '扩展 MCPB-')); const env = isolatedEnvironment(join(root, 'profile')); const signal = new AbortController().signal; const zip = join(root, 'fixture.mcpb')
    const manifest = { manifest_version: '0.3', name: 'fixture', version: '1.0.0', compatibility: { platforms: ['win32'] }, user_config: { sample: { type: 'string', required: true } }, server: { type: 'node', entry_point: 'server.mjs', mcp_config: { command: 'node', args: ['${__dirname}/server.mjs'], env: { EXAMPLE: '${user_config.sample}' } } } }
    const require = createRequire(import.meta.url); const source = `import {Server} from ${JSON.stringify(pathToFileURL(require.resolve('@modelcontextprotocol/server')).href)}; import {StdioServerTransport} from ${JSON.stringify(pathToFileURL(require.resolve('@modelcontextprotocol/server/stdio')).href)}; const s=new Server({name:'mcpb',version:'1'},{capabilities:{tools:{}}}); s.setRequestHandler('tools/list',()=>({tools:[{name:'read_config',inputSchema:{type:'object'}}]})); s.setRequestHandler('tools/call',()=>({content:[{type:'text',text:process.env.EXAMPLE}]})); await s.connect(new StdioServerTransport());`
    await command(python.executable, ['-I', '-X', 'utf8', '-c', 'import zipfile,sys; z=zipfile.ZipFile(sys.argv[1],"w"); z.writestr("manifest.json",sys.argv[2]); z.writestr("server.mjs",sys.argv[3]); z.close()', zip, JSON.stringify(manifest), source], root, env, signal)
    const bytes = await readFile(zip); const store: any = { getEntity: () => undefined, listEntities: () => [], saveEntity: () => {}, deleteEntity: () => {}, getSecret: async () => '', setSecret: async () => {}, getProject: () => undefined }; const options: ExtensionOptions = { store, stateDir: root, runtime, fetch: async () => new Response(bytes), openExternal: async () => {}, emit: () => {} }; const installer = new ExtensionInstaller(options)
    const entry: CatalogEntry = { id: 'qa', kind: 'mcp', name: 'QA', description: '', version: '1', status: 'active', packages: [{ registryType: 'mcpb', identifier: 'https://github.com/qa/fixture/releases/download/v1/fixture.mcpb', fileSha256: (await import('node:crypto')).createHash('sha256').update(bytes).digest('hex'), transport: { type: 'stdio' } }] }; const directory = join(root, 'installed'); await mkdir(directory); const revision: Revision = { id: 'r', extensionId: 'e', entry, directory, values: {}, secretKeys: [], tools: [] }; await installer.install(entry, { kind: 'mcp', id: entry.id, values: { sample: '中文配置' } }, revision, signal, () => {}); expect(revision.command?.env.EXAMPLE).toBe('中文配置'); expect(revision.command?.args[0]).toBe(join(directory, 'bundle').replaceAll('\\', '\\') + '/server.mjs'); expect(revision.runtimeIds).toEqual(['node'])
    const connection = new McpConnection(options, revision); try { await connection.connect(signal); const tools = await connection.tools(signal); expect(tools.map(tool => tool.name)).toEqual(['read_config']); const result: any = await connection.invoke(tools[0], {}, signal); expect(result.content[0].text).toBe('中文配置') } finally { await connection.close() }
    const bad = join(root, 'bad.zip'); await command(python.executable, ['-I', '-X', 'utf8', '-c', 'import zipfile,sys; z=zipfile.ZipFile(sys.argv[1],"w"); z.writestr("../outside.txt","escape"); z.close()', bad], root, env, signal); await expect(unzip(bad, join(root, 'unsafe'), signal)).rejects.toThrow(); expect(existsSync(join(root, 'outside.txt'))).toBe(false)
  }, 30000)
})
