import { contextBridge, ipcRenderer } from 'electron'
import type { AppAPI, AppEvent } from '../shared/types'

const invoke = async <T>(channel: string, input?: unknown): Promise<T> => {
  const response: { ok: boolean; value?: T; error?: string } = await ipcRenderer.invoke(channel, input)
  if (!response.ok) throw new Error(response.error ?? '操作失败')
  return response.value as T
}
const api: AppAPI = {
  editorState: () => invoke('editor:state'),
  editorEnable: enabled => invoke('editor:enable', enabled),
  editorSelectExecutable: () => invoke('editor:select'),
  editorInstall: () => invoke('editor:install'),
  editorResolveConnection: input => invoke('editor:resolve-connection', input),
  editorRevoke: id => invoke('editor:revoke', id),
  editorDismiss: id => invoke('editor:dismiss', id),
  editorApply: input => invoke('editor:apply', input),
  editorImport: input => invoke('editor:import', input),
  editorOpen: input => invoke('editor:open', input),
  editorOpenSource: id => invoke('editor:open-source', id),
  editorSend: input => invoke('editor:send', input),
  closeWindow: () => invoke('app:close-window'),
  setWindowCloseGuard: enabled => invoke('app:close-guard', enabled),
  getNetworkState: () => invoke('network:state'),
  importNetworkSubscription: input => invoke('network:import', input),
  refreshNetworkSubscription: id => invoke('network:refresh', id),
  removeNetworkSubscription: id => invoke('network:remove', id),
  testNetworkNode: input => invoke('network:test-node', input),
  testNetworkNodes: input => invoke('network:test-nodes', input),
  cancelNetworkTests: id => invoke('network:cancel-tests', id),
  saveNetworkBindings: input => invoke('network:bindings', input),
  restartNetworkCore: () => invoke('network:restart'),
  bootstrap: () => invoke('app:bootstrap'),
  previewLegacyRecovery: () => invoke('recovery:preview'),
  importLegacyRecovery: input => invoke('recovery:import', input),
  testStructuredModel: input => invoke('provider:test-structured', input),
  listComponents: () => invoke('component:list'),
  prepareComponent: id => invoke('component:prepare', id),
  importComponent: input => invoke('component:import', input),
  selectComponentFiles: () => invoke('component:select'),
  cancelComponent: id => invoke('component:cancel', id),
  removeComponent: id => invoke('component:remove', id),
  extensionState: () => invoke('extension:state'),
  searchExtensions: input => invoke('extension:search', input),
  extensionDetails: input => invoke('extension:details', input),
  installExtension: input => invoke('extension:install', input),
  updateExtension: input => invoke('extension:update', input),
  removeExtension: id => invoke('extension:remove', id),
  cancelExtensionJob: id => invoke('extension:cancel', id),
  clearExtensionJob: id => invoke('extension:clear-job', id),
  clearFinishedExtensionJobs: () => invoke('extension:clear-finished'),
  extensionPopularity: input => invoke('extension:popularity', input),
  testExtension: id => invoke('extension:test', id),
  configureExtension: input => invoke('extension:configure', input),
  saveExtensionGrant: input => invoke('extension:grant', input),
  resolveExtensionApproval: input => invoke('extension:approve', input),
  checkExtensionUpdates: () => invoke('extension:updates'),
  loginExtension: id => invoke('extension:login', id),
  importMcpConfiguration: input => invoke('extension:import-mcp', input),
  importSkill: input => invoke('extension:import-skill', input),
  saveExtensionSearchBinding: input => invoke('extension:search-binding', input),
  removeExtensionSearchBinding: projectId => invoke('extension:search-unbind', projectId),
  inspectDocument: input => invoke('document:inspect', input),
  previewDocument: input => invoke('document:preview', input),
  saveProject: input => invoke('project:save', input),
  removeProject: id => invoke('project:remove', id),
  selectDirectory: () => invoke('project:select'),
  readProjectFiles: input => invoke('project:files', input),
  readProjectFile: input => invoke('project:file', input),
  openProjectPath: input => invoke('project:open', input),
  saveDraft: input => invoke('draft:save', input),
  getDraft: id => invoke('draft:get', id),
  createExecution: input => invoke('execution:create', input),
  executionAction: input => invoke('execution:action', input),
  deleteExecution: id => invoke('execution:delete', id),
  agentStatus: () => invoke('agent:status'),
  agentPrepare: kind => invoke('agent:prepare', kind),
  agentLogin: input => invoke('agent:login', input),
  agentOpenClaude: () => invoke('agent:open-claude'),
  agentLogout: kind => invoke('agent:logout', kind),
  saveTemplate: input => invoke('template:save', input),
  deleteTemplate: id => invoke('template:delete', id),
  branchSession: input => invoke('session:branch', input),
  muteParticipant: input => invoke('session:mute', input),
  summarizeSession: input => invoke('session:summarize', input),
  searchSession: input => invoke('session:search', input),
  searchWeb: query => invoke('search:web', query),
  saveProvider: input => invoke('provider:save', input),
  removeProvider: id => invoke('provider:remove', id),
  discoverModels: input => invoke('provider:discover', input),
  testModel: model => invoke('provider:test', model),
  testToolModel: model => invoke('provider:test-tools', model),
  saveSettings: input => invoke('settings:save', input),
  createSession: input => invoke('session:create', input),
  sessionAction: input => invoke('session:action', input),
  interject: input => invoke('session:interject', input),
  deleteSession: id => invoke('session:delete', id),
  exportSession: id => invoke('session:export', id),
  createKnowledgeBase: input => invoke('knowledge:create', input),
  deleteKnowledgeBase: id => invoke('knowledge:delete', id),
  rebuildKnowledgeBase: input => invoke('knowledge:rebuild', input),
  selectFiles: () => invoke('source:select'),
  importSources: input => invoke('source:import', input),
  cancelImport: id => invoke('source:cancel', id),
  deleteSource: id => invoke('source:delete', id),
  searchKnowledge: input => invoke('knowledge:search', input),
  getSourceChunks: id => invoke('source:chunks', id),
  openSource: input => invoke('source:open', input),
  openExternal: url => invoke('app:external', url),
  onEvent: callback => {
    const listener = (_event: Electron.IpcRendererEvent, event: AppEvent): void => callback(event)
    ipcRenderer.on('app:event', listener)
    return () => ipcRenderer.removeListener('app:event', listener)
  }
}
contextBridge.exposeInMainWorld('roundtable', api)
